In [4]:
import numpy as np

## numpy array

In [5]:
benimListem = [20,30,40]

In [6]:
type(benimListem)

list

In [7]:
np.array(benimListem)

array([20, 30, 40])

In [8]:
matrixListesi = [[10,20,30],[20,30,40],[30,40,50]]

In [9]:
np.array(matrixListesi)

array([[10, 20, 30],
       [20, 30, 40],
       [30, 40, 50]])

## arange

In [10]:
list(range(0,10))

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [11]:
np.arange(0,10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

## zeros

In [12]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [13]:
np.zeros((9,9))

array([[0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0.]])

## ones

In [14]:
np.ones(5)

array([1., 1., 1., 1., 1.])

In [15]:
np.ones((3,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

## linspace

In [16]:
np.linspace(0,10,5)

array([ 0. ,  2.5,  5. ,  7.5, 10. ])

## eye

In [17]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

## random

In [18]:
np.random.randn(4)

array([ 1.1338184 , -0.34793059,  0.08104583,  0.02882616])

In [19]:
np.random.randn(4,4)

array([[-0.22855648,  0.42883861,  1.66878385,  0.88375707],
       [ 0.47402432, -0.42122633,  1.48394413, -0.89209493],
       [ 0.14881844, -1.65861286, -1.12286757, -0.85290087],
       [ 2.21496244,  0.11400918,  0.22732145,  0.75270799]])

In [20]:
np.random.randint(1,10)

1

In [21]:
np.random.randint(1,300,5)

array([129, 216,  58, 171,  56])

In [22]:
numpyDizim =np.arange(30)

In [23]:
numpyDizim

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29])

In [24]:
randomDizim = np.random.randint(0,100,20)

In [25]:
randomDizim

array([42,  9, 19, 10, 16, 69, 57, 88, 35,  3, 36, 21,  8, 94, 45, 26,  9,
        8, 99, 72])

## numpy dizi methotları

In [26]:
numpyDizim.reshape(6,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29]])

In [27]:
numpyDizim.max()

29

In [29]:
randomDizim.max()

99

In [30]:
randomDizim.min()

3

In [31]:
randomDizim.argmax()

18

In [32]:
randomDizim.argmin()

9

In [33]:
numpyDizim.shape

(30,)

In [34]:
numpyDizim

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29])

In [36]:
reshapeDizim = numpyDizim.reshape(5,6)

In [37]:
reshapeDizim

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29]])