In [1]:
import numpy as np

In [2]:
benimDizim = np.arange(0,15)

In [3]:
benimDizim

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [4]:
benimDizim[5]

5

In [6]:
benimDizim[5:8]

array([5, 6, 7])

In [7]:
benimDizim[3:8] = -5

In [8]:
benimDizim

array([ 0,  1,  2, -5, -5, -5, -5, -5,  8,  9, 10, 11, 12, 13, 14])

In [9]:
baskaDizi = np.arange(0,24)

In [10]:
baskaDizi

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23])

In [11]:
slicingDizisi = baskaDizi[4:9]

In [12]:
slicingDizisi

array([4, 5, 6, 7, 8])

In [13]:
slicingDizisi[:] =700

In [14]:
slicingDizisi

array([700, 700, 700, 700, 700])

In [15]:
baskaDizi

array([  0,   1,   2,   3, 700, 700, 700, 700, 700,   9,  10,  11,  12,
        13,  14,  15,  16,  17,  18,  19,  20,  21,  22,  23])

In [18]:
ornekDizi = np.arange(0,24)

In [19]:
ornekDizi

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23])

In [20]:
ornekDiziKopyasi = ornekDizi.copy()

In [21]:
ornekDiziKopyasi

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23])

In [22]:
ornekDizi 

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23])

In [23]:
ornekDiziKopyasiSlicing = ornekDiziKopyasi[3:6]

In [24]:
ornekDiziKopyasiSlicing[:] = 800

In [25]:
ornekDiziKopyasiSlicing

array([800, 800, 800])

In [26]:
ornekDizi

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23])

## matrix

In [27]:
listem = [[10,20,30],[20,30,40],[40,50,60]]

In [28]:
matrixDizisi = np.array(listem)

In [29]:
matrixDizisi

array([[10, 20, 30],
       [20, 30, 40],
       [40, 50, 60]])

In [30]:
matrixDizisi[0]

array([10, 20, 30])

In [34]:
matrixDizisi[1,2]

40

In [35]:
matrixDizisi[1][2]

40

In [36]:
matrixDizisi[1:,2]

array([40, 60])

In [38]:
matrixDizisi[0:,2]

array([30, 40, 60])

In [39]:
matrixDizisi[0:,0:]

array([[10, 20, 30],
       [20, 30, 40],
       [40, 50, 60]])

In [40]:
matrixDizisi[2:,0:]

array([[40, 50, 60]])

In [42]:
yeniDizi = np.arange(0,25)

In [43]:
yeniDizi

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [45]:
yeniMatrix = yeniDizi.reshape(5,5)

In [46]:
yeniMatrix

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [47]:
yeniMatrix[2]

array([10, 11, 12, 13, 14])

In [49]:
yeniMatrix[[4,2,0]]

array([[20, 21, 22, 23, 24],
       [10, 11, 12, 13, 14],
       [ 0,  1,  2,  3,  4]])

## operasyonlar

In [50]:
yeniDizi = np.random.randint(1,100,20)

In [51]:
yeniDizi

array([ 9, 63, 87, 12, 23, 47, 40, 61, 96, 70, 89, 54, 73, 14, 29, 76, 52,
       43, 53, 38])

In [56]:
sonucDizisi = yeniDizi > 24

In [57]:
sonucDizisi

array([False,  True,  True, False, False,  True,  True,  True,  True,
        True,  True,  True,  True, False,  True,  True,  True,  True,
        True,  True])

In [58]:
yeniDizi

array([ 9, 63, 87, 12, 23, 47, 40, 61, 96, 70, 89, 54, 73, 14, 29, 76, 52,
       43, 53, 38])

In [59]:
yeniDizi[sonucDizisi]

array([63, 87, 47, 40, 61, 96, 70, 89, 54, 73, 29, 76, 52, 43, 53, 38])

In [60]:
yeniDizi[yeniDizi > 24]

array([63, 87, 47, 40, 61, 96, 70, 89, 54, 73, 29, 76, 52, 43, 53, 38])

In [61]:
sonDizi = np.arange(0,24)

In [62]:
sonDizi

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23])

In [63]:
sonDizi + sonDizi

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32,
       34, 36, 38, 40, 42, 44, 46])

In [65]:
sonDizi * sonDizi

array([  0,   1,   4,   9,  16,  25,  36,  49,  64,  81, 100, 121, 144,
       169, 196, 225, 256, 289, 324, 361, 400, 441, 484, 529])

In [67]:
sonDizi - sonDizi

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0])

In [69]:
np.sqrt(sonDizi)

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ,
       3.16227766, 3.31662479, 3.46410162, 3.60555128, 3.74165739,
       3.87298335, 4.        , 4.12310563, 4.24264069, 4.35889894,
       4.47213595, 4.58257569, 4.69041576, 4.79583152])

In [70]:
np.max(sonDizi)

23

In [71]:
np.min(sonDizi)

0